# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SQLite_Database' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SQLite_Database
  pod 'SQLite.swift', '~> 0.13.3'
  target 'SQLite_DatabaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SQLite_DatabaseUITests' do
    # Pods for testing
  end

end
